import { Box, Button, TextField, Typography, useTheme } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { parseCookies } from "nookies";
import { useEffect, useState } from "react";
import { useLocalStorage } from "../hooks/useLocalStorage";
import { userNameKey } from "../store/localStorageKey";

const Home: NextPage = () => {

	const router = useRouter()
	
  const {
    palette: { primary, secondary },
    
  } = useTheme();

	const [userName, setUserName] = useLocalStorage(userNameKey,'')
	const [userNameError, setUserNameError] = useState('')

	const navigateToShowCards = () => {
		
		if(!userName){
			setUserNameError('Campo requerido')
			return
		}
		router.push('/showcards')
	}

	useEffect(() => {setUserName('')},[])

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bgcolor={"white"} height={"100vh"}>
        <Box
          display={"flex"}
          justifyContent="center"
          alignItems={"center"}
          height="100vh"
        >
          <Box
            display={"flex"}
            bgcolor={primary.main}            
            borderRadius={"2rem"}
            justifyContent="center"
            flexDirection={"column"}
            alignItems={"center"}
						py={5}
						px={6}
          >
            <Box marginBottom={3}>
              <Typography color={"white"} variant="h3">
                Quer jogar?
              </Typography>
							
            </Box>
            <Box>
              <TextField
                variant="filled"
                label="Digite seu nome"
                inputProps={{
                  style: {
                    background: secondary.contrastText,
                    borderRadius: 10,
                  },
                }}
								onChange={e => {
									if(userNameError){
										setUserNameError('')
									}
									setUserName(e.target.value)
								}}
								error={!!userNameError}
								helperText={userNameError}
              />
              <Box display={"flex"} justifyContent="flex-end" marginTop={4}>
                
                  <Button variant="contained" color="secondary" onClick={navigateToShowCards}>
                    Ver as cartas
                  </Button>
                
              </Box>
            </Box>
          </Box>
        </Box>
      </Box>
    </div>
  );
};

export default Home;
