import { Box, Button, Container, Grid, Input, useTheme } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { Card } from "../components/Card";

const Home: NextPage = () => {
  const {
    palette: { primary },
    breakpoints,
  } = useTheme();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bgcolor={primary.main} height={"100vh"}>
        <Box>
					<Input />
				</Box>
      </Box>
    </div>
  );
};

export default Home;
