import { Box, Button, TextField, Typography, useTheme } from "@mui/material";
import { Container } from "@mui/system";
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Home: NextPage = () => {
  const {
    palette: { primary, secondary },
    breakpoints,
  } = useTheme();
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box bgcolor={"white"} height={"100vh"}>
        <Box
          display={"flex"}
          justifyContent="center"
          alignItems={"center"}
          height="100vh"
        >
          <Box
            display={"flex"}
            bgcolor={primary.main}
            width={"30%"}
            height="40%"
            borderRadius={"2rem"}
            justifyContent="center"
            flexDirection={"column"}
            alignItems={"center"}
          >
            <Box marginBottom={3}>
              <Typography color={"white"} variant="h3">
                Quer jogar?
              </Typography>
							
            </Box>
            <Box>
              <TextField
                variant="filled"
                label="Digite seu nome"
                inputProps={{
                  style: {
                    background: secondary.contrastText,
                    borderRadius: 10,
                  },
                }}
              />
              <Box display={"flex"} justifyContent="flex-end" marginTop={4}>
                <Link href="/showcards">
                  <Button variant="contained" color="secondary">
                    Ver as cartas
                  </Button>
                </Link>
              </Box>
            </Box>
          </Box>
        </Box>
      </Box>
    </div>
  );
};

export default Home;
