import { Box, Button,  Container, Grid } from "@mui/material";
import Head from "next/head";
import { Card } from "../../components/Card";

export default function ShowCards() {
  return (
    <div>
      <Head>
        <title>Cartas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="md">
        
          <Box
            justifyContent={"center"}
            display="flex"
            alignItems={"center"}
            height="10rem"
            gap={3}
          >
            <Button variant="contained" color="secondary">
              Nova Carta
            </Button>
            <Button variant="contained" color="secondary">
              Nova Carta
            </Button>
          </Box>
          <Grid
          container
          rowSpacing={2}	
          alignContent="center"
          justifyContent="center"
        >
          <Grid item xs={7} sm={7} md={5} lg={3}>
            <Card />
          </Grid>
          <Grid item xs={7} sm={7} md={5} lg={3}>
            <Card />
          </Grid>
          <Grid item xs={7} sm={7} md={5} lg={3}>
            <Card />
          </Grid>
          <Grid item xs={7} sm={7} md={5} lg={3}>
            <Card />
          </Grid>
          <Grid item xs={7} sm={7} md={5} lg={3}>
            <Card />
          </Grid>
          <Grid item xs={7} sm={7} md={5} lg={3}>
            <Card />
          </Grid>
          <Grid item xs={7} sm={7} md={5} lg={3}>
            <Card />
          </Grid>
          <Grid item xs={7} sm={7} md={5} lg={3}>
            <Card />
          </Grid>
        </Grid>
      </Container>
    </div>
  );
}
