import {
  Box,
  Button,
  Container,
  Grid,
  Typography,
  useTheme,
} from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";
import { parseCookies } from "nookies";
import { useEffect } from "react";
import { Card } from "../../components/Card";
import { useCardsContext } from "../../hooks/CardsContext";
import { userNameKey } from "../../store/localStorageKey";

export default function ShowCards() {
  const { data, loading, handlePushOne, handleShuffleCards } =
    useCardsContext();

		const router = useRouter()
  const cookies = parseCookies();
  const { palette } = useTheme();

	
	useEffect(() => {
		if(!cookies[userNameKey]){
			router.push('/')
			alert("Por favor preencha seu nome")		
		}	
	},[])
  function handlePushOneCard() {
    if (data.length >= 8) {
			alert('Você não pode adicionar mais cartas')
			return
		}
    handlePushOne();
  }

  return (
    <div>
      <Head>
        <title>Cartas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        justifyContent={"center"}
        display="flex"
        alignItems={"center"}
        height="10rem"
        gap={3}
      >
        <Button
          variant="contained"
          color="secondary"
          onClick={handleShuffleCards}
        >
          Embaralhar
        </Button>
        <Button
          variant="contained"
          color="secondary"
          onClick={handlePushOneCard}
        >
          Nova Carta
        </Button>
        <Box
          position={"absolute"}
          top={10}
          right={'15%'}
          bgcolor={palette.secondary.main}
          px={2}
          py={1}
          borderRadius={3}
        >
          <Typography variant="subtitle1" color={'white'}>{cookies[userNameKey]}</Typography>
        </Box>
      </Box>
      <Box
        px={5}
        display={"flex"}
        justifyContent="center"
        gap={1}
        flexWrap={"wrap"}
      >
        {data.map((item) => {
          return (
            <Box key={Math.random()}>
              <Card item={item} />
            </Box>
          );
        })}
      </Box>
    </div>
  );
}
