import { Box, Button, Container, Grid } from "@mui/material";
import Head from "next/head";
import { Card } from "../../components/Card";
import { useCardsContext } from "../../hooks/CardsContext";

export default function ShowCards() {
  const { data, loading, handlePushOne, handleShuffleCards } =
    useCardsContext();

  function handlePushOneCard() {
    if (data.length >= 8) return;
    handlePushOne();
  }

  return (
    <div>
      <Head>
        <title>Cartas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        justifyContent={"center"}
        display="flex"
        alignItems={"center"}
        height="10rem"
        gap={3}
      >
        <Button variant="contained" color="secondary" onClick={handleShuffleCards}>
          Embaralhar
        </Button>
        <Button
          variant="contained"
          color="secondary"
          onClick={handlePushOneCard}
        >
          Nova Carta
        </Button>
      </Box>
      <Box
        px={5}
        display={"flex"}
        justifyContent="center"
        gap={1}
        flexWrap={"wrap"}
      >
        {data.map((item) => {
          return (
            <Box key={Math.random()}>
              <Card item={item} />
            </Box>
          );
        })}
      </Box>
    </div>
  );
}
